services:
- docker

language: cpp
dist: xenial
os: linux

git:
  autocrlf: false

addons:
  apt:
    sources:
      - sourceline: 'deb http://dl.bintray.com/igagis/ubuntu xenial main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x379CE192D401AB61'
    update: true
    packages:
    - binfmt-support
    - qemu-user-static
    - myci
  homebrew:
    update: true
    taps:
    - igagis/tap
    packages:
    - myci

matrix:
  include:
    - name: macosx
      os: osx
      compiler: clang
      osx_image: xcode11.3
    - name: ios
      os: osx
      compiler: clang
      osx_image: xcode11.3
    - name: android
      language: android
      android:
        components:
          - platform-tools
          - tools
          - build-tools-28.0.3
          - android-28
#          - sys-img-armeabi-v7a-android-22
          - extra-android-m2repository
    - name: msys2
      os: windows

env:
  global:
  # Encrypted MYCI_BINTRAY_API_KEY for publishing to bintray.
  - secure: "VEVeMqpL5QYqrbpcCJnF6yBvQsA9iapDKOrOGXRcCbjg1DPsWtaXK5g8wZ8HcHajcfhwa3j1pTgc64C7rMbUriiLZ7rfZ1thBbGrCEnMwGjxMvmW/L/RWVEosPR5IZI+rBaD0979lfmR6NiawwsgVLV6WdZWyLaIpfLrYL6K6CJm7nKsN0qG5GTS/MkfZstFhhS4RzcTYzOYCou9+orjKwlF38Ba7mEZVoFfSDMS/gebgBEA2JplvgU3S0Co/TMuCR2NB7MHlNX3n8WivX1TXtV5OBHZt51tzliJCKsmgRROyczoObt+PLVk/NMjzGG3juHhvihCB0sDuwPpGxl8wUG3Hq2zpUgqyIHSrueT7H9FOOHRvRuCooid5eIItPaWNg4aDRfCQGG/uYHqnn3eB+iHDi1uCjYWyvGpaiCb2v1n34iRTTG3Du/l0qS9Dtiur4fHqTlUY0sTG9ictOg5qyJRAROuHnLCehG+rDq8v0ms9gt5HGYbr3v4RGYvrWTkno/vIz1NPobfeXhPaA3BjaslszHqDNppUnW6svaSRsuRmTjLjjlRmYrw5JuPghNQ51LFjwdG0XHgl1v3vz559wAVN8rxx2AHPJPvJpw9teSuHd2uB+yN94be7nwqjVp9HhVRecdy0drWK+/UKe8nCK3Ltur6Phw3+wZpTfUeCT8="
  # Encrypted MYCI_GIT_ACCESS_TOKEN for publishing to git-based repos.
  - secure: "LNXW5q2WJHAPhrx3K07hbKeeGL3+AQJdvOg4U+sEZ0VeKVTSk7ZO3804TTsLSls7wPFz8lXmAKhU2W8DOdEUGzNGhYbWnYtUnIj6r4avezQ8AlGxKfVAkHs+gpzBl8FGZs6joAuwL4NhH93uKSJip2J3ncBtCpjmgzGYk+nimZ8xl70uGPvRLVGCXZbdOOwu7WZ2264jels+V+TuuXBj6Fcl/iBWjSe5WD/txPcLGdQkAlng7ckmUwyzSbgvFBCi1CtZktkwVwlVd2AYzBF/tBq6Ypq7QEYJtP3rwRaTo5r5MY8ul6dxs7QnNkiCU4QUZrNWYSsJOhSUckvkk+P0UwLiHdG3Tc5GUN9lTPS3Rs3gLhHOHKpnpjA4GJNGQpqZIw9zSCU9+csTeX9GHQBEL29PTfkBeT6vyfVadDTo9gg0aGI8mzypIhS+D1zUdHGNEf0rF4oVODkaVnpSr2HweTjIIP8zRHERqE27opbTWmr4hdg+GWnIZSIH5iqiAvc8Ex9eJZ9mwPUkARKqFzUxn+D8Sn8kPOCE65DcllcOij2V+E7KHESdDoTikLILnPxbJmbWooDPmgNPDRAQmqf2MHGfIzWB5cx7LEQn1bQBtlt72YxPO7BsPMMmbFDLelsKVBWxduWWpc3hbGP/K2JyzU/V0kvTDYgban69NKRWh7g="
  - MYCI_GIT_USERNAME=igagis
  - PACKAGE_NAME=morda
  matrix:
# Ubuntu
  # - OS_REL=xenial OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=bionic OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=eoan OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
# Debian
  # - OS_REL=stretch OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=buster OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=buster OS=debian DOCKER_IMAGE=i386/$OS:$OS_REL PACKAGE_TYPE=deb
# Raspbian
  # - OS_REL=stretch OS=raspbian DOCKER_IMAGE=igagis/$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=buster OS=raspbian DOCKER_IMAGE=igagis/$OS:$OS_REL PACKAGE_TYPE=deb

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker run --name ccc -v $TRAVIS_BUILD_DIR/..:/build -w /build/$(basename $TRAVIS_BUILD_DIR) -it -d $DOCKER_IMAGE bash &&
    if [ "$PACKAGE_TYPE" == "deb" ]; then
      docker exec ccc apt update &&
      docker exec ccc apt install -y dirmngr &&
      docker exec ccc bash -c "echo 'deb http://dl.bintray.com/igagis/$OS $OS_REL main' > /etc/apt/sources.list.d/igagis.list" &&
      docker exec ccc apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
      docker exec ccc apt update &&
      docker exec ccc apt install -y devscripts equivs myci &&
      myci-deb-prepare.sh;
    fi;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    brew install prorab prorab-extra libutki libpapki libpuu libsvgren z glew freetype r4 libnitki libpng;
  fi
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    sudo gem install cocoapods &&
    pod repo add --silent igagis https://$MYCI_GIT_USERNAME:$MYCI_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=xcode;
  fi
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    choco upgrade --no-progress -y msys2 &&
    export msys2="/c/tools/msys64/msys2_shell.cmd -defterm -no-start -msys -here -c" &&
    $msys2 "echo -e '[igagis_msys]\\nSigLevel = Optional TrustAll\\nServer = https://dl.bintray.com/igagis/msys2/msys' >> /etc/pacman.conf" &&
    $msys2 "echo -e '[igagis_mingw64]\\nSigLevel = Optional TrustAll\\nServer = https://dl.bintray.com/igagis/msys2/mingw64' >> /etc/pacman.conf" &&
    $msys2 "echo -e '[igagis_mingw32]\\nSigLevel = Optional TrustAll\\nServer = https://dl.bintray.com/igagis/msys2/mingw32' >> /etc/pacman.conf" &&
    $msys2 "pacman -Sy --noconfirm myci mingw-w64-x86_64-toolchain mingw-w64-i686-toolchain";
  fi
- if [ "$TRAVIS_OS_NAME" == "linux" ] || [ "$TRAVIS_OS_NAME" == "osx" ]; then
    export PACKAGE_VERSION=$(myci-deb-version.sh debian/changelog);
  fi

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc myci-deb-install-build-deps.sh;
  fi
# Accept android SDK licenses and install android tools
- if [ "$TRAVIS_JOB_NAME" == "android" ]; then
    echo y | sdkmanager "ndk-bundle" &&
    echo y | sdkmanager "cmake;3.6.4111459";
  fi

before_script:
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    curl -L https://github.com/zackslash/Xcode-Proj-Adder/raw/master/bin/XcodeProjAdder -O &&
    chmod +x XcodeProjAdder &&
    (cd xcode/$PACKAGE_NAME && ../../XcodeProjAdder -XCP $PACKAGE_NAME.xcodeproj -SCSV `echo $(find ../../src/morda -type f -name *.cpp) | sed -E -e 's/ /,/g'`)
  fi
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    $msys2 "myci-apply-version.sh -v \$(myci-deb-version.sh debian/changelog) msys2/PKGBUILD.in";
  fi

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc dpkg-buildpackage -us -uc;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    make && make test;
  fi
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    xcodebuild -workspace xcode/$PACKAGE_NAME.xcworkspace -scheme $PACKAGE_NAME CONFIGURATION_BUILD_DIR=../build -configuration Release &&
    myci-create-zip-package.sh -f res/morda_res///res -h src/morda -f xcode/build/lib$PACKAGE_NAME.a///lib/ios -f LICENSE $PACKAGE_NAME-$PACKAGE_VERSION.zip;
  fi
- if [ "$TRAVIS_JOB_NAME" == "android" ]; then
    (cd android && ./gradlew copy_aar) &&
    myci-apply-version.sh -v $PACKAGE_VERSION android/*.pom.in &&
    myci-apply-version.sh -v $PACKAGE_VERSION android/*.aar.in --filename-only;
  fi
# running MSYS2 script from deployment provider did not work for some reason, so we do it here if the commit is a tagged one.
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    $msys2 "(cd msys2 && PKGEXT='.pkg.tar.xz' makepkg-mingw --syncdeps --noconfirm --skipinteg)" &&
    if [ ! -z "$TRAVIS_TAG" ]; then
      for f in $(find msys2 -name "mingw-w64-x86_64-$PACKAGE_NAME-*-any.pkg.*"); do
        $msys2 "myci-deploy-pacman-bintray.sh -u igagis -r msys2 -p mingw64 -d igagis_mingw64 $f";
      done &&
      for f in $(find msys2 -name "mingw-w64-i686-$PACKAGE_NAME-*-any.pkg.*"); do
        $msys2 "myci-deploy-pacman-bintray.sh -u igagis -r msys2 -p mingw32 -d igagis_mingw32 $f";
      done;
    fi;
  fi


before_deploy:


deploy:
- provider: script
  skip_cleanup: true
  on:
    tags: true
    condition: $PACKAGE_TYPE = deb && -z "$TRAVIS_JOB_NAME"
  script: myci-deploy-debian-bintray.sh -u igagis -r $OS -p $PACKAGE_NAME -c main -d $OS_REL $TRAVIS_BUILD_DIR/../*.deb
- provider: script
  skip_cleanup: true
  script: myci-deploy-maven-bintray.sh -u igagis -r android -d io/github/igagis -p $PACKAGE_NAME -v $PACKAGE_VERSION android/$PACKAGE_NAME-$PACKAGE_VERSION.aar
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = android
- provider: script
  skip_cleanup: true
  script: myci-deploy-homebrew.sh -t igagis/tap
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = macosx
- provider: script
  skip_cleanup: true
  script: myci-deploy-cocoapods.sh -r igagis -v $PACKAGE_VERSION -u igagis -b cocoapods -p $PACKAGE_NAME-$PACKAGE_VERSION.zip cocoapods/$PACKAGE_NAME.podspec.in
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = ios
