language: cpp
sudo: required
dist: trusty
osx_image: xcode8.2


env:
  global:
  #encrypted HOMEBREW_GITHUB_ACCESS_TOKEN for publishing to homebrew-tap
  - secure: "xxmSoh63zIzuDGn1kkfVd1s3qNOpuyhvXzN/b6/PnCcyzSC5wfflH+PswfvYOyrDk9/FS3hzEBf8MOyfhaZ1+YXkscXINej9Cl8uhYntDRrmVCL72RKJyVZD6lu66X7gOVWuXeQB8vcGOz2vFWKbz12jA3yRlWCrmDlTz2RPckGT9ssmNBFgKRDeMIWtl3i98hfke1vyj+3bkxYXb4MR1RCb/yAbcNUAf0o8ihlXGKynPqHJN7UxGBwWUiZi9QcCFKhPwnkrc3yYu4jm0JIwqn+uwAGwes4cV2GWVD4l8kD1NybKAj0r9Fq6uq3R4qI6397hBkBafjeUQLWtf6w54Ti1sFr7ifdxtCY7HXRrhmAGKisxu8h0XiA38l0IpVf9XaGQsqiiWKp2LP9wBtWOw5ga3+wxzcavDBsGe6pIIf+NffiEvwhWoC1wSCDmhJ+9Hphi4lYspr2+WS325FlCVcwWP6gxb6ZUst/siRnQWpYhfAmI28rBVRR2ChyjkDDpnsNxBVxgHTJqPdutZLdece9oF8UxGYNgh39Mr7Eb+to1RrcD7v+IZT4RgTaBPQzp+M1Tstvk07J48ukG+dh67g6gXzQv6ZtaQKCeZaW6Z1dw4k/sgEJE3wWXoFi/6RkbqAB338sye83HefloaGbzaAwC4pQxGZqa2dgOH70jmSs="
  - PRORAB_GIT_USERNAME=igagis
  - PRORAB_GIT_ACCESS_TOKEN=$HOMEBREW_GITHUB_ACCESS_TOKEN
  - linuxDependencies="debhelper lintian pkg-config prorab doxygen libutki-dev libnitki-dev libpapki-dev libunikod-dev libkolme-dev libstob-dev libsvgren-dev libpng-dev libjpeg-dev zlib1g-dev libglew-dev libfreetype6-dev"


matrix:
  include:
    - os: osx
      env: BUILD_NAME=macosx
      compiler: clang
    - os: osx
      env: BUILD_NAME=ios
      compiler: clang
    - os: linux
      env: BUILD_NAME=debian
      compiler: gcc
    - os: linux
      env: BUILD_NAME=ubuntu
      compiler: gcc
    - os: linux
      env: BUILD_NAME=raspberry_pi
      compiler: gcc
#    - os: linux
#      env: BUILD_NAME=clang
#      compiler: clang


before_install:
- if [ "$BUILD_NAME" == "macosx" ]; then
    brew tap igagis/tap &&
    brew update > /dev/null &&
    (brew list libpng || brew install libpng) &&
    brew install prorab libutki libpapki libunikod libstob libsvgren jpeg z glew freetype libkolme libnitki;
  fi
- if [ "$BUILD_NAME" == "ios" ]; then
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install prorab &&

    rvm install ruby-2.2.2 &&
    rvm use ruby-2.2.2 &&
    sudo gem install cocoapods &&
    pod repo add --silent igagis https://$PRORAB_GIT_USERNAME:$PRORAB_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=ios;
  fi
- if [ "$BUILD_NAME" == "debian" ]; then
    echo "deb http://dl.bintray.com/igagis/deb unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild prorab debhelper &&
    sudo sbuild-adduser $LOGNAME &&
    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
    sudo sbuild-createchroot --include=gnupg1,dirmngr,build-essential testing /srv/chroot/deb-amd64 http://httpredir.debian.org/debian &&
    echo "deb [trusted=yes] http://dl.bintray.com/igagis/deb unstable main" | sudo tee /srv/chroot/deb-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
    echo 'APT::Get { AllowUnauthenticated "1"; };' | sudo tee /srv/chroot/deb-amd64/etc/apt/apt.conf.d/80unauthenticate > /dev/null &&
    sudo chroot /srv/chroot/deb-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo chroot /srv/chroot/deb-amd64 ln -s /usr/bin/gpg1 /usr/bin/gpg;
  fi
- if [ "$BUILD_NAME" == "ubuntu" ]; then
    echo "deb http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild prorab debhelper &&
    sudo sbuild-adduser $LOGNAME &&
    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
    sudo sbuild-createchroot --include=gnupg,dirmngr,build-essential --components=main,universe xenial /srv/chroot/ubu-amd64 http://archive.ubuntu.com/ubuntu/ &&
    echo "deb [trusted=yes] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /srv/chroot/ubu-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/ubu-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61;
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    echo "deb http://dl.bintray.com/igagis/deb unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq prorab;
    sudo prorab-make-raspberry-chroot.sh -d jessie /srv/chroot/rasp-armhf &&
    echo "deb http://dl.bintray.com/igagis/rasp unstable main" | sudo tee /srv/chroot/rasp-armhf/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/rasp-armhf apt-get update &&
    sudo chroot /srv/chroot/rasp-armhf apt-get install --allow-unauthenticated -qq -y $linuxDependencies &&
    sudo chroot /srv/chroot/rasp-armhf sed -i -e 's/jessie/testing/g' /etc/apt/sources.list &&
    sudo chroot /srv/chroot/rasp-armhf apt-get update &&
    sudo chroot /srv/chroot/rasp-armhf apt-get install --allow-unauthenticated -qq -y g++ &&
    sudo mkdir -p /srv/chroot/rasp-armhf/build &&
    sudo rsync -av $TRAVIS_BUILD_DIR/ /srv/chroot/rasp-armhf/build/;
  fi
- if [ "$BUILD_NAME" == "clang" ]; then
    echo "deb http://dl.bintray.com/igagis/deb /" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq $linuxDependencies lintian;
  fi



script:
- if [ "$BUILD_NAME" == "debian" ]; then
    prorab-deb-prepare.sh &&
    sg sbuild -c "sbuild -A -d testing-amd64-sbuild --run-lintian --debbuildopts '-us -uc'";
  fi
- if [ "$BUILD_NAME" == "ubuntu" ]; then
    prorab-deb-prepare.sh &&
    sg sbuild -c "sbuild -A -d xenial-amd64-sbuild --debbuildopts '-us -uc'";
  fi
- if [ "$BUILD_NAME" == "clang" ]; then
    prorab-deb-prepare.sh &&
    dpkg-buildpackage -uc -us;
  fi
- if [ "$BUILD_NAME" == "macosx" ]; then
    make;
  fi
# need to reduce output from xcodebuild because log size on travis-ci is limited by 4Mb, use grep for errors and warnings
# Also, need to set pipefail to make pipe exit code nono-zero in case first command fails but second succeeds (because grep exits with 0 always)
- if [ "$BUILD_NAME" == "ios" ]; then
    set -o pipefail &&
    xcodebuild -workspace ios/morda_test.xcworkspace -scheme morda_test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
            | sed -e "s/export PATH=[^ ]*/export PATH=.../g"
            | sed -e "s/[^ ]*\/clang /clang /g"
            | sed -e "s/\(-[IWfFL]\)[^ ]*/% /g"
            | sed -e "s/-isystem [^ ]*/%/g"
            | sed -e "s/-include [^ ]*/%/g"
            | sed -e "s/-MF [^ ]*/-MF .../g"
            | sed -e "s/--serialize-diagnostics [^ ]*/%/g"
            | sed -e "s/-o [^ ]*/%/g"
            | sed -e "s/-iquote [^ ]*/%/g"
            | sed -e "s/-isysroot [^ ]*/%/g";
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && prorab-deb-prepare.sh" &&
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && ogles2=true dpkg-buildpackage -us -uc";
  fi
  
  

before_deploy:
  - prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` travis_bintray_*.json.in


deploy:
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = debian
  file: travis_bintray_deb.json
  user: igagis
  key:
    secure: "I9Y/BFy451N+PtWur7BXB6MFyqdUaUmrOYbLc2YrTEnKCloaGifGKjQN2VqRuVoj92R7xaPYmd+GnXFs/f5pozmucJNDNDHwd0VVQM29kaETFKY4gsfkBt6ura185Ok/thzSPwmMMmDU6y3sAGoLSC2dGAiz/V3ol0qVGZnGdqa1mOjBJJkRq6TVNjU490GLBc7xSPmObKUouFpFfKfpuWjkBf9n2uEFe/d5Q3TAEPvbj/5ZccRO2r1aJv3s/5/pZuv8Va+MKCp6hCmvsIFw5Gkg8n/50Yd0jj2K+NTnT43nyUPoxq4BLDulC0e4ww0rtKQl5BBW8q7yqYRsw3vNZog71NLFBxpVwSLwe4LHJM0XP4Z3HOPo/GWCekG4ex2Bw02BeOvAv1IAifRJrETgkJ6bF7WPkn80C6AyLZ86BPrsJKKeeL95gELOoEPfEesQKFgglBvSXShP6jZANrmAY4vJ605Wtq2IRksjb9VISCCrCjRwZ221RHdcOaX28ibt2J086RxBxcVOxewVEX0m7Q/HklfUaxorUenejOltcvdG//Jz0eKgJou+1XOFxHP3FiROlHylIc9hgRjhpr344PZ4penlAx1mqbRAX+J0eqQzXGi6ihrEaOo5eSme5RNumSmC3ehaODB3+D+NRzeW4/iqErnrALeOGGTPSnCWf8E="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = ubuntu
  file: travis_bintray_ubu.json
  user: igagis
  key:
    secure: "I9Y/BFy451N+PtWur7BXB6MFyqdUaUmrOYbLc2YrTEnKCloaGifGKjQN2VqRuVoj92R7xaPYmd+GnXFs/f5pozmucJNDNDHwd0VVQM29kaETFKY4gsfkBt6ura185Ok/thzSPwmMMmDU6y3sAGoLSC2dGAiz/V3ol0qVGZnGdqa1mOjBJJkRq6TVNjU490GLBc7xSPmObKUouFpFfKfpuWjkBf9n2uEFe/d5Q3TAEPvbj/5ZccRO2r1aJv3s/5/pZuv8Va+MKCp6hCmvsIFw5Gkg8n/50Yd0jj2K+NTnT43nyUPoxq4BLDulC0e4ww0rtKQl5BBW8q7yqYRsw3vNZog71NLFBxpVwSLwe4LHJM0XP4Z3HOPo/GWCekG4ex2Bw02BeOvAv1IAifRJrETgkJ6bF7WPkn80C6AyLZ86BPrsJKKeeL95gELOoEPfEesQKFgglBvSXShP6jZANrmAY4vJ605Wtq2IRksjb9VISCCrCjRwZ221RHdcOaX28ibt2J086RxBxcVOxewVEX0m7Q/HklfUaxorUenejOltcvdG//Jz0eKgJou+1XOFxHP3FiROlHylIc9hgRjhpr344PZ4penlAx1mqbRAX+J0eqQzXGi6ihrEaOo5eSme5RNumSmC3ehaODB3+D+NRzeW4/iqErnrALeOGGTPSnCWf8E="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = raspberry_pi
  file: travis_bintray_rasp.json
  user: igagis
  key:
    secure: "I9Y/BFy451N+PtWur7BXB6MFyqdUaUmrOYbLc2YrTEnKCloaGifGKjQN2VqRuVoj92R7xaPYmd+GnXFs/f5pozmucJNDNDHwd0VVQM29kaETFKY4gsfkBt6ura185Ok/thzSPwmMMmDU6y3sAGoLSC2dGAiz/V3ol0qVGZnGdqa1mOjBJJkRq6TVNjU490GLBc7xSPmObKUouFpFfKfpuWjkBf9n2uEFe/d5Q3TAEPvbj/5ZccRO2r1aJv3s/5/pZuv8Va+MKCp6hCmvsIFw5Gkg8n/50Yd0jj2K+NTnT43nyUPoxq4BLDulC0e4ww0rtKQl5BBW8q7yqYRsw3vNZog71NLFBxpVwSLwe4LHJM0XP4Z3HOPo/GWCekG4ex2Bw02BeOvAv1IAifRJrETgkJ6bF7WPkn80C6AyLZ86BPrsJKKeeL95gELOoEPfEesQKFgglBvSXShP6jZANrmAY4vJ605Wtq2IRksjb9VISCCrCjRwZ221RHdcOaX28ibt2J086RxBxcVOxewVEX0m7Q/HklfUaxorUenejOltcvdG//Jz0eKgJou+1XOFxHP3FiROlHylIc9hgRjhpr344PZ4penlAx1mqbRAX+J0eqQzXGi6ihrEaOo5eSme5RNumSmC3ehaODB3+D+NRzeW4/iqErnrALeOGGTPSnCWf8E="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: prorab-deploy-homebrew.sh -t igagis/tap homebrew/libmorda.rb.in && prorab-deploy-homebrew.sh -t igagis/tap homebrew/libmorda-opengl2-ren.rb.in
  on:
    tags: true
    condition: $BUILD_NAME = macosx
- provider: script
  skip_cleanup: true
  script: rvm 2.2.1 do prorab-deploy-cocoapods.sh igagis
  on:
    tags: true
    condition: $BUILD_NAME = ios
