branches:
  except:
  - release

sudo: required

matrix:
  include:
    - os: osx
      env: BUILD_NAME=macosx
      compiler: clang
      language: cpp
      osx_image: xcode8.2
    - os: osx
      env: BUILD_NAME=ios
      compiler: clang
      language: cpp
      osx_image: xcode8.2
    - os: linux
      env: BUILD_NAME=debian
      compiler: gcc
      language: cpp
      dist: trusty
    - os: linux
      env: BUILD_NAME=ubuntu
      compiler: gcc
      language: cpp
      dist: trusty
    - os: linux
      env: BUILD_NAME=raspberry_pi
      compiler: gcc
      language: cpp
      dist: trusty
    - env: BUILD_NAME=android
      language: android


android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
#    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository


env:
  global:
  #encrypted PRORAB_GIT_ACCESS_TOKEN for publishing to git-based repos
  - secure: "FNE3Acgtq2RylOClapr3c/VBouuRUud/ITkeVN+fqvblkKYuzew/e4KNF6bz0tkI1+xYybDamFDVXg6WifMYiBQL5zrgFBr1olRhlC7FQc4za0Saw8nJOwBMm2MPvi/gogpbOe5VaO1y9sRYC/JtfDntO4JJo8XU6D5SKtMt1cNDsPUXFD6Anvgab9rXdoxSBxQMpw2dd/ykfFpLfn4uNQ1cxlf7o5u5rTvQaHS6Pk+gJC5irHuSx4459x+k56wSpWqyLzcF3lVI6vqqwqLKXTRzNsaf5mCRsSX43unrAfmeQOyA+/XXDAeMfUZdppwLoUugYQ4wui4wQIzLJzGtI2TUb+KIOzTOZFRk7ePr240Q8YZ3In6D8uCBmw1WCafO6pGFjXqMUKwfQSgonU7Cmh5AN2dqkOZbUGmdgO82rKSMVE3WjSTEYuQM+Tf9WTdHpEp912ANBk4RJtN6jCXjhG5ZAjAZAOoR5xqWUKnMJFwlrYP6EKNMMAF0551vAPwbQ+J9zqVawJKouJT61mCi9T0sAbNqKw65PPcLn9JyluQgtpXeNRmmFte0zJ0mNwLBtFF2n6A5umE52YZnRQz8immtdwh2buDOGHfX9jO+HaHQ4lMuh10nqlaY1bh+g11vmb08oGoZaefVZuZ5S92J2hjquPVa6GYX+Asc5KYtHlg="
  - PRORAB_GIT_USERNAME=igagis
  - USE_ANDROID_NDK_VERSION=15c
  - linuxDependencies="debhelper lintian pkg-config prorab doxygen libutki-dev libnitki-dev libpapki-dev libunikod-dev libkolme-dev libstob-dev libsvgren-dev libpng-dev libjpeg-dev zlib1g-dev libglew-dev libfreetype6-dev"



before_install:
- if [ "$BUILD_NAME" == "macosx" ]; then
    brew tap igagis/tap &&
    brew update > /dev/null &&
    (brew list libpng || brew install libpng) &&
    (brew list jpeg || brew install jpeg) &&
    brew install prorab libutki libpapki libunikod libstob libsvgren z glew freetype libkolme libnitki;
  fi
- if [ "$BUILD_NAME" == "ios" ]; then
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install prorab &&

    brew install --force openssl &&
    rvm install ruby-2.2.1 &&
    rvm install ruby-2.2.2 &&
    rvm use ruby-2.2.2 &&
    
    rvm 2.2.1 do gem uninstall bundler -v '>1.12.5' --force &&
    rvm 2.2.1 do gem install bundler -v 1.12.5 --no-rdoc --no-ri --no-document --quiet &&
    
    sudo gem install cocoapods &&
    rvm 2.2.1 do gem install cocoapods &&
    pod repo add --silent igagis https://$PRORAB_GIT_USERNAME:$PRORAB_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=ios;
  fi
- if [ "$BUILD_NAME" == "android" ]; then
    echo "deb [arch=amd64] https://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq prorab;
  fi
- if [ "$BUILD_NAME" == "debian" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild prorab debhelper &&
    sudo sbuild-adduser $LOGNAME &&
    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
    sudo sbuild-createchroot --include=gnupg1,dirmngr,build-essential testing /srv/chroot/deb-amd64 http://httpredir.debian.org/debian &&
    echo "deb [trusted=yes] http://dl.bintray.com/igagis/deb unstable main" | sudo tee /srv/chroot/deb-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
    echo 'APT::Get { AllowUnauthenticated "1"; };' | sudo tee /srv/chroot/deb-amd64/etc/apt/apt.conf.d/80unauthenticate > /dev/null &&
    sudo chroot /srv/chroot/deb-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo chroot /srv/chroot/deb-amd64 ln -s /usr/bin/gpg1 /usr/bin/gpg;
  fi
- if [ "$BUILD_NAME" == "ubuntu" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild prorab debhelper &&
    sudo sbuild-adduser $LOGNAME &&
    echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
    echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
    sudo sbuild-createchroot --include=gnupg,dirmngr,build-essential --components=main,universe xenial /srv/chroot/ubu-amd64 http://archive.ubuntu.com/ubuntu/ &&
    echo "deb [trusted=yes] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /srv/chroot/ubu-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/ubu-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61;
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq prorab;
    sudo prorab-make-raspberry-chroot.sh /srv/chroot/rasp-armhf &&
    echo "deb http://dl.bintray.com/igagis/rasp unstable main" | sudo tee /srv/chroot/rasp-armhf/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/rasp-armhf sed -i -e 's/jessie/testing/g' /etc/apt/sources.list &&
    sudo chroot /srv/chroot/rasp-armhf apt-get update &&
    sudo chroot /srv/chroot/rasp-armhf apt-get install --allow-unauthenticated -qq -y $linuxDependencies g++ &&
    sudo mkdir -p /srv/chroot/rasp-armhf/build &&
    sudo rsync -av $TRAVIS_BUILD_DIR/ /srv/chroot/rasp-armhf/build/;
  fi


before_script:
  # download and install android NDK
  - if [ "$BUILD_NAME" == "android" ]; then
      export TERM=dumb &&
      curl -L https://dl.google.com/android/repository/android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip -O &&
      unzip ./android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip > /dev/null &&
      rm android-ndk-r$USE_ANDROID_NDK_VERSION-linux-x86_64.zip &&
      export ANDROID_NDK_HOME=`pwd`/android-ndk-r$USE_ANDROID_NDK_VERSION &&
      export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME" &&
      export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64" &&
      export PATH=$PATH:${ANDROID_NDK_HOME} &&
      env;
    fi

script:
- if [ "$BUILD_NAME" == "debian" ]; then
    prorab-deb-prepare.sh &&
    sg sbuild -c "sbuild -A -d testing-amd64-sbuild --run-lintian --debbuildopts '-us -uc'";
  fi
- if [ "$BUILD_NAME" == "ubuntu" ]; then
    prorab-deb-prepare.sh &&
    sg sbuild -c "sbuild -A -d xenial-amd64-sbuild --debbuildopts '-us -uc'";
  fi
- if [ "$BUILD_NAME" == "macosx" ]; then
    make && make test;
  fi
# need to reduce output from xcodebuild because log size on travis-ci is limited by 4Mb, use grep for errors and warnings
# Also, need to set pipefail to make pipe exit code nono-zero in case first command fails but second succeeds (because grep exits with 0 always)
- if [ "$BUILD_NAME" == "ios" ]; then
    set -o pipefail &&
    xcodebuild -workspace ios/morda_test.xcworkspace -scheme morda_test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
            | sed -e "s/export PATH=[^ ]*/export PATH=.../g"
            | sed -e "s/[^ ]*\/clang /clang /g"
            | sed -e "s/\(-[IWfFL]\)[^ ]*/% /g"
            | sed -e "s/-isystem [^ ]*/%/g"
            | sed -e "s/-include [^ ]*/%/g"
            | sed -e "s/-MF [^ ]*/-MF .../g"
            | sed -e "s/--serialize-diagnostics [^ ]*/%/g"
            | sed -e "s/-o [^ ]*/%/g"
            | sed -e "s/-iquote [^ ]*/%/g"
            | sed -e "s/-isysroot [^ ]*/%/g";
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && prorab-deb-prepare.sh" &&
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && ogles2=true dpkg-buildpackage -us -uc";
  fi
- if [ "$BUILD_NAME" == "android" ]; then
    (cd android && ./gradlew build) &&
    prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` android/*.pom.in &&
    prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` android/*.aar.in --filename-only;
  fi
  

before_deploy:
  - prorab-apply-version.sh -v `prorab-deb-version.sh debian/changelog` travis_bintray_*.json.in


deploy:
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = debian
  file: travis_bintray_deb.json
  user: igagis
  key:
    secure: "I9Y/BFy451N+PtWur7BXB6MFyqdUaUmrOYbLc2YrTEnKCloaGifGKjQN2VqRuVoj92R7xaPYmd+GnXFs/f5pozmucJNDNDHwd0VVQM29kaETFKY4gsfkBt6ura185Ok/thzSPwmMMmDU6y3sAGoLSC2dGAiz/V3ol0qVGZnGdqa1mOjBJJkRq6TVNjU490GLBc7xSPmObKUouFpFfKfpuWjkBf9n2uEFe/d5Q3TAEPvbj/5ZccRO2r1aJv3s/5/pZuv8Va+MKCp6hCmvsIFw5Gkg8n/50Yd0jj2K+NTnT43nyUPoxq4BLDulC0e4ww0rtKQl5BBW8q7yqYRsw3vNZog71NLFBxpVwSLwe4LHJM0XP4Z3HOPo/GWCekG4ex2Bw02BeOvAv1IAifRJrETgkJ6bF7WPkn80C6AyLZ86BPrsJKKeeL95gELOoEPfEesQKFgglBvSXShP6jZANrmAY4vJ605Wtq2IRksjb9VISCCrCjRwZ221RHdcOaX28ibt2J086RxBxcVOxewVEX0m7Q/HklfUaxorUenejOltcvdG//Jz0eKgJou+1XOFxHP3FiROlHylIc9hgRjhpr344PZ4penlAx1mqbRAX+J0eqQzXGi6ihrEaOo5eSme5RNumSmC3ehaODB3+D+NRzeW4/iqErnrALeOGGTPSnCWf8E="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = ubuntu
  file: travis_bintray_ubu.json
  user: igagis
  key:
    secure: "I9Y/BFy451N+PtWur7BXB6MFyqdUaUmrOYbLc2YrTEnKCloaGifGKjQN2VqRuVoj92R7xaPYmd+GnXFs/f5pozmucJNDNDHwd0VVQM29kaETFKY4gsfkBt6ura185Ok/thzSPwmMMmDU6y3sAGoLSC2dGAiz/V3ol0qVGZnGdqa1mOjBJJkRq6TVNjU490GLBc7xSPmObKUouFpFfKfpuWjkBf9n2uEFe/d5Q3TAEPvbj/5ZccRO2r1aJv3s/5/pZuv8Va+MKCp6hCmvsIFw5Gkg8n/50Yd0jj2K+NTnT43nyUPoxq4BLDulC0e4ww0rtKQl5BBW8q7yqYRsw3vNZog71NLFBxpVwSLwe4LHJM0XP4Z3HOPo/GWCekG4ex2Bw02BeOvAv1IAifRJrETgkJ6bF7WPkn80C6AyLZ86BPrsJKKeeL95gELOoEPfEesQKFgglBvSXShP6jZANrmAY4vJ605Wtq2IRksjb9VISCCrCjRwZ221RHdcOaX28ibt2J086RxBxcVOxewVEX0m7Q/HklfUaxorUenejOltcvdG//Jz0eKgJou+1XOFxHP3FiROlHylIc9hgRjhpr344PZ4penlAx1mqbRAX+J0eqQzXGi6ihrEaOo5eSme5RNumSmC3ehaODB3+D+NRzeW4/iqErnrALeOGGTPSnCWf8E="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = raspberry_pi
  file: travis_bintray_rasp.json
  user: igagis
  key:
    secure: "I9Y/BFy451N+PtWur7BXB6MFyqdUaUmrOYbLc2YrTEnKCloaGifGKjQN2VqRuVoj92R7xaPYmd+GnXFs/f5pozmucJNDNDHwd0VVQM29kaETFKY4gsfkBt6ura185Ok/thzSPwmMMmDU6y3sAGoLSC2dGAiz/V3ol0qVGZnGdqa1mOjBJJkRq6TVNjU490GLBc7xSPmObKUouFpFfKfpuWjkBf9n2uEFe/d5Q3TAEPvbj/5ZccRO2r1aJv3s/5/pZuv8Va+MKCp6hCmvsIFw5Gkg8n/50Yd0jj2K+NTnT43nyUPoxq4BLDulC0e4ww0rtKQl5BBW8q7yqYRsw3vNZog71NLFBxpVwSLwe4LHJM0XP4Z3HOPo/GWCekG4ex2Bw02BeOvAv1IAifRJrETgkJ6bF7WPkn80C6AyLZ86BPrsJKKeeL95gELOoEPfEesQKFgglBvSXShP6jZANrmAY4vJ605Wtq2IRksjb9VISCCrCjRwZ221RHdcOaX28ibt2J086RxBxcVOxewVEX0m7Q/HklfUaxorUenejOltcvdG//Jz0eKgJou+1XOFxHP3FiROlHylIc9hgRjhpr344PZ4penlAx1mqbRAX+J0eqQzXGi6ihrEaOo5eSme5RNumSmC3ehaODB3+D+NRzeW4/iqErnrALeOGGTPSnCWf8E="
  dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = android
  file: travis_bintray_android.json
  user: igagis
  key:
    secure: "I9Y/BFy451N+PtWur7BXB6MFyqdUaUmrOYbLc2YrTEnKCloaGifGKjQN2VqRuVoj92R7xaPYmd+GnXFs/f5pozmucJNDNDHwd0VVQM29kaETFKY4gsfkBt6ura185Ok/thzSPwmMMmDU6y3sAGoLSC2dGAiz/V3ol0qVGZnGdqa1mOjBJJkRq6TVNjU490GLBc7xSPmObKUouFpFfKfpuWjkBf9n2uEFe/d5Q3TAEPvbj/5ZccRO2r1aJv3s/5/pZuv8Va+MKCp6hCmvsIFw5Gkg8n/50Yd0jj2K+NTnT43nyUPoxq4BLDulC0e4ww0rtKQl5BBW8q7yqYRsw3vNZog71NLFBxpVwSLwe4LHJM0XP4Z3HOPo/GWCekG4ex2Bw02BeOvAv1IAifRJrETgkJ6bF7WPkn80C6AyLZ86BPrsJKKeeL95gELOoEPfEesQKFgglBvSXShP6jZANrmAY4vJ605Wtq2IRksjb9VISCCrCjRwZ221RHdcOaX28ibt2J086RxBxcVOxewVEX0m7Q/HklfUaxorUenejOltcvdG//Jz0eKgJou+1XOFxHP3FiROlHylIc9hgRjhpr344PZ4penlAx1mqbRAX+J0eqQzXGi6ihrEaOo5eSme5RNumSmC3ehaODB3+D+NRzeW4/iqErnrALeOGGTPSnCWf8E="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: prorab-deploy-homebrew.sh -t igagis/tap homebrew/libmorda.rb.in
  on:
    tags: true
    condition: $BUILD_NAME = macosx
- provider: script
  skip_cleanup: true
  script: rvm 2.2.1 do prorab-deploy-cocoapods.sh -r igagis
  on:
    tags: true
    condition: $BUILD_NAME = ios
