language: cpp
sudo: required
dist: trusty
osx_image: xcode7.3

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  exclude:
    - os: osx
      compiler: gcc

env:
  global:
  #encrypted HOMEBREW_GITHUB_ACCESS_TOKEN for publishing to homebrew-tap
  - secure: "xxmSoh63zIzuDGn1kkfVd1s3qNOpuyhvXzN/b6/PnCcyzSC5wfflH+PswfvYOyrDk9/FS3hzEBf8MOyfhaZ1+YXkscXINej9Cl8uhYntDRrmVCL72RKJyVZD6lu66X7gOVWuXeQB8vcGOz2vFWKbz12jA3yRlWCrmDlTz2RPckGT9ssmNBFgKRDeMIWtl3i98hfke1vyj+3bkxYXb4MR1RCb/yAbcNUAf0o8ihlXGKynPqHJN7UxGBwWUiZi9QcCFKhPwnkrc3yYu4jm0JIwqn+uwAGwes4cV2GWVD4l8kD1NybKAj0r9Fq6uq3R4qI6397hBkBafjeUQLWtf6w54Ti1sFr7ifdxtCY7HXRrhmAGKisxu8h0XiA38l0IpVf9XaGQsqiiWKp2LP9wBtWOw5ga3+wxzcavDBsGe6pIIf+NffiEvwhWoC1wSCDmhJ+9Hphi4lYspr2+WS325FlCVcwWP6gxb6ZUst/siRnQWpYhfAmI28rBVRR2ChyjkDDpnsNxBVxgHTJqPdutZLdece9oF8UxGYNgh39Mr7Eb+to1RrcD7v+IZT4RgTaBPQzp+M1Tstvk07J48ukG+dh67g6gXzQv6ZtaQKCeZaW6Z1dw4k/sgEJE3wWXoFi/6RkbqAB338sye83HefloaGbzaAwC4pQxGZqa2dgOH70jmSs="
  - HOMEBREW_GITHUB_USERNAME=igagis

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    echo "deb https://dl.bintray.com/igagis/deb /" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq debhelper prorab doxygen libutki-dev libpapki-dev libunikod-dev libaika-dev libkolme-dev libstob-dev libsvgren-dev libpng-dev libjpeg-dev zlib1g-dev libglew-dev libfreetype6-dev;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    rvm use ruby-2.2.1 &&
    pod repo add --silent igagis https://$HOMEBREW_GITHUB_USERNAME:$HOMEBREW_GITHUB_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=ios &&
    
    brew tap igagis/tap &&
    brew update > /dev/null &&
    (brew list libpng || brew install libpng) &&
    brew install prorab libutki libpapki libunikod libaika libstob libsvgren jpeg z glew freetype libkolme;
  fi


script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    prorab-deb-prepare.sh &&
    dpkg-buildpackage -us -uc;
  fi

# need to reduce output from xcodebuild because log size on travis-ci is limited by 4Mb, use grep for errors and warnings
# Also, need to set pipefail to make pipe exit code nono-zero in case first command fails but second succeeds (because grep exits with 0 always)
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    make &&
    
    set -o pipefail &&
    xcodebuild -workspace ios/morda_test.xcworkspace -scheme morda_test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | grep -E -A 5 "(error|warning):" &&

    if [ -n "$TRAVIS_TAG" ]; then prorab-deploy-cocoapods.sh igagis; else echo "Skip deploying to cocoapods because not a tagged commit!!!"; fi;
  fi

before_deploy:
  - prorab-apply-version.sh `prorab-deb-version.sh debian/changelog` travis_bintray.json.in

deploy:
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux && $CC = gcc
  file: travis_bintray.json
  user: igagis
  key:
    secure: "I9Y/BFy451N+PtWur7BXB6MFyqdUaUmrOYbLc2YrTEnKCloaGifGKjQN2VqRuVoj92R7xaPYmd+GnXFs/f5pozmucJNDNDHwd0VVQM29kaETFKY4gsfkBt6ura185Ok/thzSPwmMMmDU6y3sAGoLSC2dGAiz/V3ol0qVGZnGdqa1mOjBJJkRq6TVNjU490GLBc7xSPmObKUouFpFfKfpuWjkBf9n2uEFe/d5Q3TAEPvbj/5ZccRO2r1aJv3s/5/pZuv8Va+MKCp6hCmvsIFw5Gkg8n/50Yd0jj2K+NTnT43nyUPoxq4BLDulC0e4ww0rtKQl5BBW8q7yqYRsw3vNZog71NLFBxpVwSLwe4LHJM0XP4Z3HOPo/GWCekG4ex2Bw02BeOvAv1IAifRJrETgkJ6bF7WPkn80C6AyLZ86BPrsJKKeeL95gELOoEPfEesQKFgglBvSXShP6jZANrmAY4vJ605Wtq2IRksjb9VISCCrCjRwZ221RHdcOaX28ibt2J086RxBxcVOxewVEX0m7Q/HklfUaxorUenejOltcvdG//Jz0eKgJou+1XOFxHP3FiROlHylIc9hgRjhpr344PZ4penlAx1mqbRAX+J0eqQzXGi6ihrEaOo5eSme5RNumSmC3ehaODB3+D+NRzeW4/iqErnrALeOGGTPSnCWf8E="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: prorab-deploy-homebrew.sh igagis/tap
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx && $CC = clang
